# SPDX-FileCopyrightText: 2026 Sophie Smithburg
# SPDX-License-Identifier: GPL-3.0-or-later

module(
    name = "ixyk",
    version = "0.0.1",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "ixyk_vendored_arpy", version = "1.1.1")
bazel_dep(name = "ixyk_vendored_mulpyplexer", version = "0.9")

local_path_override(
    module_name = "ixyk_vendored_arpy",
    path = "third_party/arpy",
)

local_path_override(
    module_name = "ixyk_vendored_mulpyplexer",
    path = "third_party/mulpyplexer",
)

python = use_extension(
    "@rules_python//python/extensions:python.bzl",
    "python",
)
python.defaults(python_version = "3.12")
python.toolchain(python_version = "3.12")

nix_python = use_extension("//tools:nix_python.bzl", "nix_python")
use_repo(nix_python, "nix_python_toolchains")

register_toolchains("@nix_python_toolchains//:all")

pip = use_extension(
    "@rules_python//python/extensions:pip.bzl",
    "pip",
)
pip.parse(
    hub_name = "ixyk_pypi",
    python_interpreter = "python3.12",
    python_version = "3.12",
    requirements_by_platform = {
        "//extractor:requirements_linux_x86_64.txt": "linux_x86_64",
    },
)

override_repo(
    pip,
    ixyk_pypi_312_arpy = "ixyk_vendored_arpy",
    ixyk_pypi_312_mulpyplexer = "ixyk_vendored_mulpyplexer",
)

use_repo(pip, "ixyk_pypi")

nix_native_deps = use_extension(
    "//tools:nix_native_deps.bzl",
    "nix_native_deps",
)
use_repo(nix_native_deps, "nix_native_deps")

bazel_dep(name = "lean_bazel", version = "0.1.0")
local_path_override(
    module_name = "lean_bazel",
    path = "third_party/lean_bazel",
)

lean_sdk = use_extension("@lean_bazel//toolchains:lean_sdk_repository.bzl", "lean_sdk")
use_repo(lean_sdk, "lean_sdk")

register_toolchains("@lean_bazel//toolchains:registered_lean_sdk")

bazel_dep(name = "zstd", version = "1.5.7.bcr.1")
