# SPDX-FileCopyrightText: 2026 Sophie Smithburg
# SPDX-License-Identifier: GPL-3.0-or-later

load("@ixyk_pypi//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "algebra",
    srcs = [
        "__init__.py",
        "algebra.py",
        "many.py",
    ],
)

py_test(
    name = "algebra_test",
    srcs = ["algebra_test.py"],
    deps = [":algebra"],
)

py_test(
    name = "algebra_property_test",
    srcs = ["algebra_property_test.py"],
    deps = [
        ":algebra",
        requirement("hypothesis"),
        requirement("pytest"),
    ],
)
